### ISSUE TITLE
Client not connecting to each other

### ISSUE THREAD

**Issue by joykirat18** [aws-samples/aws-gamelift-and-serverless-backend-sample#6]
Hi, 

I have followed all the steps but still, 2 clients are not able to connect with each other and it time out after 20 seconds. I am currently using the 202 unity version. Can you please guide how can I solve this problem?

Thanks

**Comment by juhoaws** [comment]
Hi,

Sorry to hear you've had issues. Because you're seeing the timeout, I expect the serverless backend is working correctly. You can view the log output in Unity on the client side to see what errors are returned from the API and also check Lambda logs in CloudWatch logs to see any errors in the Lambda function output.

It's very possible that GameLift is not able to allocate a session for you for some reason. Possible causes include:

1. The game server is not working correctly. You can use GameLift Local to test in Unity that the game server connects to GameLift correctly (https://docs.aws.amazon.com/gamelift/latest/developerguide/integration-testing-local.html)

2. The Fleet is not active. You can check the GameLift management console that your GameLift Fleet has active game servers in both locations. The fleet deployment could fail because the game server binary name is not correct (check the Readme for details) or because you have exceeded your instance limits for GameLift in a region. Check the CloudFormation stack output in the management console as well for any errors.

Let me know if this helps and we can figure out more debugging options if needed!
